language: cpp
compiler: gcc
dist: bionic

install:
  - sudo apt update
  - sudo apt install libglfw3-dev libglew-dev libglm-dev libgl1-mesa-dev

before_script:
  - mkdir build
  - cd build
  - cmake --version
  - cmake -DBUILD_PLAYGROUND=false ..  # don't build the application

script:
  - make -j4
