language: cpp
compiler: gcc
dist: bionic

install:
  - sudo apt update
  - sudo apt install libglfw3-dev libglew-dev libglm-dev libgl1-mesa-dev
  - cd thirdparty/assimp # install assimp for building
  - cmake .
  - make
  - sudo make install

before_script:
  - mkdir build
  - cd build
  - cmake --version
  - cmake ..

script:
  - make -j4
